pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/manuverma123/devops.git']])
            }
        }
        
         stage('build') {
            steps {
               bat '"C:\\Program Files\\apache-maven-3.9.1\\bin\\mvn.cmd" -f "Exitest-API\'s\\pom.xml" clean install'
            }
         }
    }
}
